# Generated by Django 4.1.3 on 2023-01-28 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 28, 18, 38, 57, 634311)),
        ),
    ]
