# Generated by Django 4.1.3 on 2023-01-30 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCL', '0002_alter_userinfo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 14, 2, 3, 951191)),
        ),
    ]
