# Generated by Django 4.1.3 on 2023-01-30 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCL', '0003_alter_userinfo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 14, 6, 19, 255434))),
                ('testname', models.CharField(max_length=150)),
                ('test_date', models.DateField()),
                ('test_time', models.TimeField()),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('verification_doc', models.FileField(upload_to='Verification Documents')),
                ('address', models.TextField()),
                ('test_price', models.IntegerField()),
                ('mop', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 14, 6, 19, 254438)),
        ),
    ]
