# Generated by Django 4.1.3 on 2023-01-30 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCL', '0004_test_info_alter_userinfo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='test_info',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 15, 10, 21, 840987)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 15, 10, 21, 840987)),
        ),
    ]
