# Generated by Django 4.1.3 on 2023-01-30 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCL', '0005_contact_alter_test_info_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 15, 12, 29, 808610))),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_info',
        ),
        migrations.DeleteModel(
            name='userinfo',
        ),
        migrations.AlterField(
            model_name='test_info',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 15, 12, 29, 808610)),
        ),
    ]
