# Generated by Django 4.1.3 on 2023-01-30 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCL', '0006_user_info_rename_contact_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_info',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 15, 17, 33, 193156)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 15, 17, 33, 192159)),
        ),
    ]
