# Generated by Django 4.1.3 on 2023-02-04 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCL', '0010_alter_contact_info_created_alter_test_info_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_info',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 18, 38, 53, 685726)),
        ),
        migrations.AlterField(
            model_name='test_info',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 18, 38, 53, 685726)),
        ),
        migrations.AlterField(
            model_name='test_info',
            name='test_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 18, 38, 53, 685726)),
        ),
    ]
